"use client";
import React, { useState } from "react";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import Joi from "joi";
import { formFieldsBirthday } from "@/content/coupon/gene-form";
import UserList from "../user-list";
import { useRouter } from "next/navigation";
import { useMutation } from "@/components/hook/useMutation";
import { toast } from "sonner";

// Define types for form data and validation errors
interface FormData {
  [key: string]: string | number;
}

interface ValidationErrors {
  [key: string]: string;
}
// Define a static Joi schema
const formSchema = Joi.object({
  discountType: Joi.string().valid("FLAT", "PERCENTAGE").required().messages({
    "any.required": "Discount Type is required.",
    "any.only": 'Discount Type must be either "flat" or "percentage".',
  }),
  discountValue: Joi.when("discountType", {
    is: "PERCENTAGE",
    then: Joi.number().min(0).max(100).required().messages({
      "number.min": "Percentage must be between 0 and 100.",
      "number.max": "Percentage must be between 0 and 100.",
    }),
    otherwise: Joi.number().min(0).required().messages({
      "number.min": "Flat discount must be greater than or equal to 0.",
    }),
  }),
  birthdayMonth: Joi.string().required().messages({
    "any.required": "Birthday Month is required.",
  }),

  minimumPurchase: Joi.number().optional().messages({
    "number.base": "Minimum Purchase Value must be a number.",
  }),
  validForCountry: Joi.string().required().messages({
    "any.required": "Valid For Country is required.",
  }),
  description: Joi.string().required().messages({
    "string.base": "Description must be a string.",
  }),
  userIds: Joi.any().required().messages({
    "any.required": "User IDs are required.",
  }),
  status: Joi.string().valid("ACTIVE", "INACTIVE").required().messages({
    "any.required": "Status is required.",
    "any.only": 'Status must be either "active" or "inactive".',
  }),
});

const BirthdayCouponForm: React.FC = () => {
  const router = useRouter();
  const { data, isLoading, mutate, error } = useMutation("/coupons", {
    method: "POST",
  });
  // Initialize form data with empty fields
  const [formData, setFormData] = useState<any>({
    discountType: "PERCENTAGE",
  });

  const [errors, setErrors] = useState<ValidationErrors>({});
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>("");

  const handleDateChange = (date: Date, fieldName: string) => {
    setFormData({
      ...formData,
      [fieldName]: date.toISOString(),
    });
  };

  // Handle changes in the form fields
  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement> | any
  ) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };
  console.log(formData, "formData");

  const validate = (): boolean => {
    const { error } = formSchema.validate(formData, { abortEarly: false });
    console.log(error, "error");

    if (error) {
      const newErrors: ValidationErrors = {};
      error.details.forEach((err) => {
        // Skip userIds validation error
        if (err.path[0] !== "userIds") {
          newErrors[err.path[0]] = err.message;
        }
      });

      setErrors(newErrors);
      return false;
    }

    setErrors({});
    return true;
  };

  // Generate a random coupon code
  const generateCouponCode = () => {
    return Math.random().toString(36).substring(2, 10).toUpperCase();
  };

  const handleCouponMethodChange = (value: string) => {
    console.log(value, "value");

    if (value === "auto") {
      const generatedCode = generateCouponCode();
      setAutoGeneratedCode(generatedCode);
      setFormData({
        ...formData,
        couponCode: generatedCode,
        couponMethod: value,
      });
    } else {
      setFormData({ ...formData, couponCode: "", couponMethod: value });
    }
  };
  function getStartEndDate(birthdayMonth: string): {
    startDate: string;
    endDate: string;
  } {
    // Map of month names to their corresponding numeric values
    const monthMap: { [key: string]: number } = {
      january: 0,
      february: 1,
      march: 2,
      april: 3,
      may: 4,
      june: 5,
      july: 6,
      august: 7,
      september: 8,
      october: 9,
      november: 10,
      december: 11,
    };

    // Convert the month string to lowercase to ensure case-insensitivity
    const monthKey = birthdayMonth.toLowerCase();

    // Get the numeric value for the month
    const monthNumber = monthMap[monthKey];

    // Check if the month is valid
    if (monthNumber === undefined) {
      throw new Error(`Invalid month: ${birthdayMonth}`);
    }

    const currentYear = new Date().getFullYear();

    // Create a date object for the first day of the selected month
    const startDate = new Date(currentYear, monthNumber, 1);

    // Calculate the last day of the month
    const lastDay = new Date(currentYear, monthNumber + 1, 0).getDate();

    // Create a date object for the last day of the selected month
    const endDate = new Date(currentYear, monthNumber, lastDay);

    // Return the dates in ISO format
    return {
      startDate: startDate.toISOString(),
      endDate: endDate.toISOString(),
    };
  }

  // Handle form submission
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const birthdayMonth = 6; // June
    const { startDate, endDate } = getStartEndDate(formData?.birthdayMonth);
    if (validate()) {
      const generatedCode = generateCouponCode();

      const final = {
        ...formData,
        couponType: "BIRTHDAY",
        couponCode: generatedCode,
        startDate,
        endDate,
      };

      mutate(final, "POST", {
        onSuccess: (response) => {
          if (response.status === 201) {
            // Show a success toast message
            toast.success("Coupon created successfully!");
            router.back();
          }
        },
        onError: (error) => {
          // Handle the error if the request fails
          toast.error("Failed to create coupon!");
          console.error("Error:", error);
        },
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      className="p-4 w-full rounded-lg border space-y-5"
    >
      {formFieldsBirthday.map((field) => {
        if (field.name === "discountType" || field.name === "discountValue") {
          return (
            <div className="">
              <label
                htmlFor={field.id}
                className="flex items-center gap-2 text-gray-700 text-sm pb-1 font-medium"
              >
                {field.label}{" "}
                {field.required && (
                  <span className="text-red-500">
                    <svg
                      width="13"
                      height="12"
                      viewBox="0 0 13 12"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M6.19515 10.5C8.69775 10.5 10.8903 8.57293 10.8903 6C10.8903 3.42707 8.69775 1.5 6.19515 1.5C3.69254 1.5 1.5 3.42707 1.5 6C1.5 8.57293 3.69254 10.5 6.19515 10.5Z"
                        fill="#F04438"
                        stroke="#FFEAE8"
                        strokeWidth="3"
                      />
                    </svg>
                  </span>
                )}
              </label>
              <div className="flex justify-between w-full items-center gap-3">
                <RadioGroup
                  defaultValue={field.defaultValue}
                  value={formData[field.name] as string}
                  onValueChange={(value) =>
                    setFormData({ ...formData, [field.name]: value })
                  }
                  className="flex space-x-24"
                >
                  {field.options?.map((option) => (
                    <div
                      key={option.value}
                      className="flex items-center space-x-2"
                    >
                      <RadioGroupItem value={option.value} id={option.value} />
                      <Label htmlFor={option.value}>{option.label}</Label>
                    </div>
                  ))}
                </RadioGroup>
                <div className="flex items-start w-[50%] flex-col">
                  <div className="relative w-full">
                    <span className="absolute top-2 left-3">
                      {field.name === "discountType"
                        ? formData["discountType"] === "FLAT"
                          ? "$"
                          : "%"
                        : "$"}
                    </span>
                    <input
                      type="text"
                      id="discountValue"
                      name="discountValue"
                      value={formData["discountValue"] as string}
                      onChange={(e) => {
                        const value = e.target.value;
                        let updatedValue = value;

                        if (formData["discountType"] === "FLAT") {
                          // Allow only numbers and ensure value is greater than or equal to 1
                          updatedValue = value.replace(/\D/g, ""); // Removes any non-digit character
                          if (parseInt(updatedValue) < 1) updatedValue = "1";
                        } else if (formData["discountType"] === "percentage") {
                          // Allow only numbers and restrict percentage between 1 and 100
                          updatedValue = value.replace(/\D/g, ""); // Removes any non-digit character
                          if (parseInt(updatedValue) < 1) updatedValue = "1";
                          if (parseInt(updatedValue) > 100)
                            updatedValue = "100";
                        }

                        handleChange({
                          target: {
                            name: "discountValue",
                            value: updatedValue,
                          },
                        });
                      }}
                      placeholder={field.placeholder}
                      className={`placeholder:text-[#667085]  pl-8 border rounded-lg py-2.5 w-full px-4 text-sm ${
                        errors["discountValue"]
                          ? "border-red-500"
                          : "border-gray-300"
                      }`}
                    />
                  </div>
                  {errors["discountValue"] && (
                    <p className="text-red-500 pt-1 text-sm">
                      {errors["discountValue"]}
                    </p>
                  )}{" "}
                </div>
              </div>
            </div>
          );
        }

        if (field.type === "userList") {
          return <UserList setFormData={setFormData} formData={formData} />;
        }

        return (
          <div key={field.name}>
            <label
              htmlFor={field.id}
              className="flex items-center gap-2 text-gray-700 text-sm pb-1 font-medium"
            >
              {field.label}{" "}
              {field.required && (
                <span className="text-red-500">
                  <svg
                    width="13"
                    height="12"
                    viewBox="0 0 13 12"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M6.19515 10.5C8.69775 10.5 10.8903 8.57293 10.8903 6C10.8903 3.42707 8.69775 1.5 6.19515 1.5C3.69254 1.5 1.5 3.42707 1.5 6C1.5 8.57293 3.69254 10.5 6.19515 10.5Z"
                      fill="#F04438"
                      stroke="#FFEAE8"
                      strokeWidth="3"
                    />
                  </svg>
                </span>
              )}
            </label>
            {field.type === "radio" ? (
              <>
                {" "}
                {field.type === "radio" && field.name === "couponMethod" ? (
                  <RadioGroup
                    onValueChange={(value) => {
                      setFormData({ ...formData, [field.name]: value });
                      handleCouponMethodChange(value);
                    }}
                    className="flex space-x-4"
                  >
                    {field.options?.map((option) => (
                      <div
                        key={option.value}
                        className="flex items-center space-x-2"
                      >
                        <RadioGroupItem
                          value={option.value}
                          id={option.value}
                        />
                        <Label htmlFor={option.value}>{option.label}</Label>
                      </div>
                    ))}
                  </RadioGroup>
                ) : field.type === "radio" ? (
                  <RadioGroup
                    value={formData[field.name] as string}
                    onValueChange={(value) =>
                      setFormData({ ...formData, [field.name]: value })
                    }
                    className="flex space-x-4"
                  >
                    {field.options?.map((option) => (
                      <div
                        key={option.value}
                        className="flex items-center space-x-2"
                      >
                        <RadioGroupItem
                          value={option.value}
                          id={option.value}
                        />
                        <Label htmlFor={option.value}>{option.label}</Label>
                      </div>
                    ))}
                  </RadioGroup>
                ) : (
                  <input
                    type={field.type}
                    id={field.id}
                    name={field.name}
                    value={formData[field.name] as string}
                    onChange={handleChange}
                    placeholder={field.placeholder}
                    className="border p-2 rounded w-full"
                    disabled={
                      field.name === "couponCode" &&
                      formData.couponMethod === "auto"
                    }
                  />
                )}
                {formData.couponMethod === "auto" && (
                  <div className="text-sm pt-4 text-green-500">
                    Auto-generated Coupon Code: {autoGeneratedCode}
                  </div>
                )}
              </>
            ) : field.type === "select" && field.options ? (
              <Select
                value={formData[field.name] as string}
                onValueChange={(value: string) =>
                  setFormData({
                    ...formData,
                    [field.name]: value,
                  })
                }
              >
                <SelectTrigger className="w-full">
                  <SelectValue placeholder={field.placeholder} />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectLabel>{field.label}</SelectLabel>
                    {field.options.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
            ) : field.type === "textarea" ? (
              <div className="">
                <textarea
                  cols={30}
                  rows={5}
                  id={field.id}
                  name={field.name}
                  value={formData[field.name] as string}
                  onChange={handleChange}
                  placeholder={field.placeholder}
                  className="border p-2 text-sm rounded-lg w-full"
                />
              </div>
            ) : (
              <div className="relative flex items-center gap-12">
                {field.name === "minimumPurchase" && (
                  <span className="absolute top-2 left-3">$</span>
                )}

                <input
                  type={field.type}
                  id={field.id}
                  name={field.name}
                  disabled={
                    field.name === "couponMethod" &&
                    formData.couponMethod === "auto"
                  }
                  value={formData[field.name] as string}
                  onChange={handleChange}
                  placeholder={field.placeholder}
                  className={`placeholder:text-[#667085] border rounded-lg py-2.5 w-full px-4 text-sm ${
                    errors[field.name] ? "border-red-500" : "border-gray-300"
                  } ${field.name === "minimumPurchase" ? "pl-8" : ""}`}
                />
                {field.name === "minimumPurchase" && (
                  <p className="text-red-500 w-full font-semibold text-xs mt-1">
                    Leave blank / Put zero if no minimum value apply
                  </p>
                )}
              </div>
            )}
            {errors[field.name] && (
              <p className="text-red-500 pt-1 text-sm">{errors[field.name]}</p>
            )}
          </div>
        );
      })}

      <div className="flex justify-center items-center px-4 pb-4 gap-4">
        <button
          type="button"
          className="px-4 py-2 rounded-lg border text-sm font-medium"
        >
          Clear
        </button>
        <button
          type="submit"
          className="bg-[#316BEB] text-white text-sm px-4 py-2 rounded-lg font-medium"
        >
          Add
        </button>
      </div>
    </form>
  );
};

export default BirthdayCouponForm;
