export const userListC = [
  {
    _id: "66fa38b9159943935a1c2515",
    userId: "007gaybarn@gmail.com",
    billAddr: [
      {
        zip: "99208",
        city: "Spokane",
        addr1: null,
        addr2: null,
        state: "Washington",
        status: "Active",
        lastName: "Barnhouse",
        firstName: "Gayle",
        countryCode: "US",
        countryName: "US",
        custCompName: null,
      },
    ],
    insertBy: "admin",
    insertTs: "2024-09-30 01:35:41.000000",
    shipAddr: [
      {
        zip: "99208",
        city: "Spokane",
        addr1: "7724 North Dakota",
        addr2: null,
        state: "Washington",
        status: "Active",
        lastName: "Barnhouse",
        firstName: "Gayle",
        countryCode: "US",
        countryName: "US",
        custCompName: null,
      },
    ],
    updateBy: "admin",
    updateTs: "2024-09-30 01:35:41.000000",
    userInfo: [
      {
        ext: null,
        fax: null,
        fbId: null,
        phone: "5099815648",
        bdDate: null,
        gender: "not_say",
        mobile: null,
        status: "Active",
        userId: 2225,
        bdMonth: null,
        orgName: null,
        AnnivDay: "",
        custName: "Gayle",
        googleId: null,
        showCity: "San Mateo, CA",
        AnnivDate: "1000-01-01",
        loginCode: "1Diamond",
        loginName: "",
        resaleNum: "",
        resellReq: 0,
        subScribe: "YES",
        AnnivMonth: null,
        isReseller: 0,
        custLastName: "Barnhouse",
      },
    ],
    creditUnit: null,
    userCoupon: null,
  },
  {
    _id: "66fa38b9159943935a1c2516",

    userId: "01jlcrawford@bellsouth.net",
    billAddr: [
      {
        zip: "29697",
        city: "Williamston",
        addr1: null,
        addr2: null,
        state: "South Carolina",
        status: "Active",
        lastName: "Crawford",
        firstName: "Julie",
        countryCode: "US",
        countryName: "US",
        custCompName: "Crawford Creek Designs",
      },
    ],
    insertBy: "admin",
    insertTs: "2024-09-30 01:35:41.000000",
    shipAddr: [
      {
        zip: "29697",
        city: "Williamston",
        addr1: "517 Foster Rd",
        addr2: null,
        state: "South Carolina",
        status: "Active",
        lastName: "Crawford",
        firstName: "Julie",
        countryCode: "US",
        countryName: "US",
        custCompName: "Crawford Creek Designs",
      },
    ],
    updateBy: "admin",
    updateTs: "2024-09-30 01:35:41.000000",
    userInfo: [
      {
        ext: null,
        fax: null,
        fbId: null,
        phone: "864-846-9430",
        bdDate: null,
        gender: "not_say",
        mobile: null,
        status: "Active",
        userId: 2968,
        bdMonth: null,
        orgName: "Crawford Creek Designs",
        AnnivDay: "",
        custName: "Julie",
        googleId: null,
        showCity: "Asheville, NC",
        AnnivDate: "1000-01-01",
        loginCode: "01julie",
        loginName: "",
        resaleNum: "",
        resellReq: 0,
        subScribe: "YES",
        AnnivMonth: null,
        isReseller: 0,
        custLastName: "Crawford",
      },
    ],
    creditUnit: null,
    userCoupon: null,
  },

  {
    _id: "66fa38b9159943935a1c2516",

    userId: "01jlcrawford@bellsouth.net",
    billAddr: [
      {
        zip: "29697",
        city: "Williamston",
        addr1: null,
        addr2: null,
        state: "South Carolina",
        status: "Active",
        lastName: "Crawford",
        firstName: "Julie",
        countryCode: "US",
        countryName: "US",
        custCompName: "Crawford Creek Designs",
      },
    ],
    insertBy: "admin",
    insertTs: "2024-09-30 01:35:41.000000",
    shipAddr: [
      {
        zip: "29697",
        city: "Williamston",
        addr1: "517 Foster Rd",
        addr2: null,
        state: "South Carolina",
        status: "Active",
        lastName: "Crawford",
        firstName: "Julie",
        countryCode: "US",
        countryName: "US",
        custCompName: "Crawford Creek Designs",
      },
    ],
    updateBy: "admin",
    updateTs: "2024-09-30 01:35:41.000000",
    userInfo: [
      {
        ext: null,
        fax: null,
        fbId: null,
        phone: "864-846-9430",
        bdDate: null,
        gender: "not_say",
        mobile: null,
        status: "Active",
        userId: 2968,
        bdMonth: null,
        orgName: "Crawford Creek Designs",
        AnnivDay: "",
        custName: "Julie",
        googleId: null,
        showCity: "Asheville, NC",
        AnnivDate: "1000-01-01",
        loginCode: "01julie",
        loginName: "",
        resaleNum: "",
        resellReq: 0,
        subScribe: "YES",
        AnnivMonth: null,
        isReseller: 0,
        custLastName: "Crawford",
      },
    ],
    creditUnit: null,
    userCoupon: null,
  },
];
